### ISSUE TITLE
Add text for Amplitude on ECG Strip Dashboard

### ISSUE THREAD

**Issue by hadi2021** [hadi2021/ECG#2]
![Amplitude Text](https://user-images.githubusercontent.com/65225449/81678548-e94e0180-9466-11ea-83c2-016ef440f5a6.JPG)

**Comment by Azam-Mokhtari** [comment]
با توجه به اینکه سعی کردیم 10ثانیه از سیگنال را در هر خط نمایش دهیم، نمیتوانیم مقیاس را بر حسب میلیمتر تعیین کنیم. بنابراین نمایش 
scale 
به تنهایی کافی است

**Comment by hadi2021** [comment]
We cancel this feature.
